/** Limites métier Backend 03 — éviter les nombres magiques dispersés. */
export const CATALOG_LIMITS = {
  MAX_JOBBER_SERVICES: 15,
  MAX_JOBBER_SKILLS: 40,
  MAX_JOBBER_SERVICE_AREAS: 20,
  MAX_SKILL_NAME_LENGTH: 120,
  MAX_HEADLINE_LENGTH: 160,
  MAX_BIO_LENGTH: 1000,
  MAX_EXPERIENCE_DESCRIPTION_LENGTH: 1000,
  MAX_YEARS_OF_EXPERIENCE: 50,
  MAX_RADIUS_KM: 200,
  DEFAULT_MINIMUM_AGE: 16,
  DEFAULT_COUNTRY_CODE: 'BJ',
} as const;

export const CATALOG_COUNTS = {
  CATEGORIES: 8,
  SERVICES: 35,
} as const;
